# Generated by Django 5.1.3 on 2024-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmenu', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='produtos/'),
        ),
    ]
