# Generated by Django 5.1.3 on 2024-11-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmenu', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to='produtos/'),
            preserve_default=False,
        ),
    ]
