# Generated by Django 5.1.3 on 2024-12-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmenu', '0005_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descriçao',
        ),
    ]
